# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

source 'https://git.oschina.net/c4605/Cocoapods-Specs.git'

pod 'STRegex', '~> 0.3.0'
pod 'Sparkle'

target 'Helium' do

end

target 'HeliumTests' do

end

target 'HeliumShareExtension' do

end

